version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Testing123
      POSTGRES_DB: dev_db
    networks:
      - wyrdnetwork
  test-db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Testing123
      POSTGRES_DB: test_db
    networks:
      - wyrdnetwork
networks:
  wyrdnetwork:
